input_string = input()
print(input_string[2])
print(input_string[-2])
print(input_string[:5])
print(input_string[:-2])
print(input_string[::2])
print(input_string[1::2])
print(input_string[::-1])
print(input_string[-1::-2])
print(len(input_string))
